from abc import ABC, abstractmethod
from typing import Generator

class LLMProvider(ABC):
    """
    Abstract base class for all Large Language Model (LLM) providers.
    Ensures that any concrete LLM provider implements a standard 'query' method.
    """

    @abstractmethod
    def query(self, system_prompt: str, user_prompt: str) -> Generator[str, None, None]:
        """
        Sends a streaming query to the LLM.

        Args:
            system_prompt: The instruction or context for the model's behavior.
            user_prompt: The user's direct question or input.

        Yields:
            Chunks of the text response as they are generated by the LLM.
        """
        pass 